server:
  port: 8101
spring:
  application:
    name: evaluate-gateway
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
    gateway:
      routes:
        - id: evaluate-user-service        # 路由规则id，自定义，唯一
          uri: lb://evaluate-user-service   # 路由的目标服务，lb代表负载均衡，会从注册中心拉取服务列表
          predicates: # 路由断言，判断当前请求是否符合当前规则，符合则路由到目标服务
            - Path=/api/user/**                 # 这里是以请求路径作为判断规则
        - id: evaluate-question-service
          uri: lb://evaluate-question-service
          predicates:
            - Path=/api/question/**
        - id: evaluate-judge-service
          uri: lb://evaluate-judge-service
          predicates:
            - Path=/api/judge/**
  main:
    web-application-type: reactive
knife4j:
  gateway:
    # ① 第一个配置，开启gateway聚合组件
    enabled: true
    # ② 第二行配置，设置聚合模式采用discover服务发现的模式
    strategy: discover
    discover:
      # ③ 第三行配置，开启discover模式
      enabled: true
      # ④ 第四行配置，聚合子服务全部为Swagger2规范的文档
      version: swagger2

